### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by seferdemirci** [ozgrozer/rss-filter#1]
Thanks for the script but I noticed a bug in the implementation. For instance, when you open these RSS which are in the below, some of the fields is disappearing (image, permalink, etc.)

original; https://t24.com.tr/rss
manipulated; https://www.seferdemirci.com/php/rss/?source=https://t24.com.tr/rss

**Comment by ozgrozer** [comment]
Tried to add the `enclosure` element [here](https://github.com/ozgrozer/rss-filter/commit/c9ebfb259c51731630ad9c2b307e44fc754cd696).

**Comment by seferdemirci** [comment]
Thanks a lot 👌
