### ISSUE TITLE
Error in feeds

### ISSUE THREAD

**Issue by devoldski** [ozgrozer/rss-filter#2]
Hi there and thank you for making this script.

I just tried it on two different rss feeds and both failed with the following error

**error on line 12 at column 103: EntityRef: expecting ';'**

https://www.aftenposten.no/rss/
https://e24.no/rss

When using your original wired feed https://www.wired.com/feed/rss works like a charm, do you have any suggestions on how to fix the script for the errors i receive?

Br
Alfa Sommersol

**Comment by ozgrozer** [comment]
It should be working now with [this](https://github.com/ozgrozer/rss-filter/commit/5295a7a06be9d893b970e52d73940c5d3ec2cb8d) commit.
